# Generated by Django 5.0.4 on 2024-05-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0002_evening_morning'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmodel',
            name='mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
